
CREATE TABLE MEMBER (
  SYS_CREATION_DATE      DATE NOT NULL
  ,SYS_UPDATE_DATE       DATE
  ,OPERATOR_ID           NUMBER(9) NOT NULL
  ,APPLICATION_ID        CHAR(6) NOT NULL
  ,MODIFIED_SERVICE_CODE CHAR(6)
  ,MEMBER_ID             NUMBER(6) NOT NULL
  ,FIRST_NAME            VARCHAR2(400)
  ,LAST_NAME             VARCHAR2(400)
  ,MEMBER_TYPE           CHAR(1)
  ,MEMBER_STATUS         VARCHAR2(4)
  ,CONSTRAINT MEMBER_ID_PK PRIMARY KEY (MEMBER_ID)
);

CREATE SEQUENCE MEMBER_ID_SEQ
  START WITH 100000
  MAXVALUE 999999
  MINVALUE 100000;